# Generated by Django 6.0.3 on 2026-04-02 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('processed', 'Processed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='ordered', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tracking_notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_update'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
